### ISSUE TITLE
Question: Can't locate inc/latest.pm

### ISSUE THREAD

**Issue by KES777** [Perl-Toolchain-Gang/inc-latest#4]
On some systems I often get error message:
```
Can't locate inc/latest.pm in @INC (you may need to install the inc::latest module) (@INC contains: /home/feelsafe/web/local/lib/perl5/x86_64-linux-gnu-thread-multi /home/feelsafe/web
/local/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/per
l/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at Makefile.PL line 51.
BEGIN failed--compilation aborted at Makefile.PL line 51.
```

Should I just install `inc::latest` system wide to fix this? or this this a bug of modules which do not include `inc::latest` as dependency?

**Comment by karenetheridge** [comment]
What Makefile.PL is giving this error?  Does that distribution include inc::latest in prereqs or bundle it locally? You have provided no context for debugging this...

**Comment by KES777** [comment]
I have `cpanfile` with some modules. I do not require `List::MoreUtils` directly. But when it is required the 0.416 version is fetched, despite on 0.428 is available.
0.416 has not [this](https://github.com/perl5-utils/List-MoreUtils/commit/16ed78677#diff-5d3ba18294715d9415e9e732852bfec6R15) patch yet

Here is logs:
```
Unpacking MooseX-Traits-Pluggable-0.12.tar.gz
...
Checking if you have List::MoreUtils 0 ... No
==> Found dependencies: List::MoreUtils
Searching List::MoreUtils on mirror index /home/feelsafe/web/local/cache/modules/02packages.details.txt ...
--> Working on List::MoreUtils
Fetching http://cpan.metacpan.org/authors/id/R/RE/REHSACK/List-MoreUtils-0.416.tar.gz
-> OK
```
The cache:
```
File:         02packages.details.txt
URL:          http://www.perl.com/CPAN/modules/02packages.details.txt
Description:  Package names found in cpanfile.snapshot
Columns:      package name, version, path
Intended-For: Automated fetch routines, namespace documentation.
Written-By:   Carton v1.0.28
Line-Count:   2744
Last-Updated: Mon May  7 16:36:42 2018

Algorithm::C3                      0.10  H/HA/HAARG/Algorithm-C3-0.10.tar.gz
...
List::MoreUtils                   0.416  R/RE/REHSACK/List-MoreUtils-0.416.tar.gz
```

From logs we can see that List::MoreUtils required by MooseX::Traits::Pluggable, but there is no restriction on version. 

Looking at the cache we can see that it says 0.416 is latest. Cache is updated today: `Last-Updated: Mon May  7 16:36:42 2018`, but from the 'URL': `http://www.perl.com/CPAN/modules/02packages.details.txt` the latest List::MoreUtils is 0.418

Here is full logs:
[02packages.details.txt](https://github.com/Perl-Toolchain-Gang/inc-latest/files/1980816/02packages.details.txt)
[build.log](https://github.com/Perl-Toolchain-Gang/inc-latest/files/1980817/build.log)

Thus this issue does not belongs to `inc::latest`. Sorry

**Comment by KES777** [comment]
But how I get wrong info about latest List::MoreUtils module for just downloaded `02packages.details.txt` file?
Maybe is this `Carton` issue?

**Comment by KES777** [comment]
I figure it out `why`.

The `cpanfile.snapshot` has:

     List-MoreUtils-0.416

Thus carton uses it, as it should do.
